### ISSUE TITLE
ln -s $VOCdevit/VOC2007 VOC2007

### ISSUE THREAD

**Issue by bheAI** [tztztztztz/yolov2.pytorch#4]
this step, there are some errors, I searched it but there are no effective solution, I tried some ways by changing the path, still didn`t work?
ln -s $VOCdevit/VOC2007 VOC2007
error:
ln: failed to creat symbolic link 'VOC2017': operation not supported.

**Comment by tztztztztz** [comment]
Is your operation system windows? Windows does not have `ln` command, you can use other commands like mklink instead.
But I would recommend simply copy the data to the specified directory.
