### ISSUE TITLE
Confirm the network is true Yolov2?

### ISSUE THREAD

**Issue by JCZ404** [tztztztztz/yolov2.pytorch#6]
Hi, thank you for such great work, but I want to confirm that it is a Yolov2 network like the one in the original paper?  Because when I look at your code, I think it seems like the Yolov1:), but you know I'm also a beginner in deep learning, so I just want to confirm this with you.  Thank you!

**Comment by tztztztztz** [comment]
Yes, the network is YOLOv2 like the original paper.
For example, it uses anchors and does classification and regression base on them. 

Let me know if you have other questions.
